apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-cicd
  template:
    metadata:
      labels:
        app: java-cicd
    spec:
      containers:
        - name: java-cicd
          image: amandevopss/amandevopss:latest
          ports:
            - containerPort: 8080
